package model;

public class CartModel {
    private int cartId;   // This will be set automatically by the database upon insertion
    private int id;
    private int prod_id;
    private int quantity;

    // Default constructor
    public CartModel() {
    }

    // Constructor with all fields except cartId, which is auto-generated by the database
    public CartModel(int id, int prod_id, int quantity) {
        this.id = id;
        this.prod_id = prod_id;
        this.quantity = quantity;
    }

    // Getters and setters
    public int getCartId() {
        return cartId;
    }

    public void setCartId(int cartId) {
        this.cartId = cartId;
    }

    public int getid() {
        return id;
    }

    public void setid(int id) {
        this.id = id;
    }

    public int getProductId() {
        return prod_id;
    }

    public void setProductId(int prod_id) {
        this.prod_id = prod_id;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
